// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsOQMeoWVgryTbLRNfS8XTKIB6sDZjtGs',
    appId: '1:467717966998:web:a44792ba243c748d69c6b7',
    messagingSenderId: '467717966998',
    projectId: 'hot-or-not-4ff4b',
    authDomain: 'hot-or-not-4ff4b.firebaseapp.com',
    storageBucket: 'hot-or-not-4ff4b.appspot.com',
    measurementId: 'G-NWRQLNE56F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALpBMUiHDP3xPkhuajlmg7BUOagBWJN-Y',
    appId: '1:467717966998:android:785d6d43a7ea384869c6b7',
    messagingSenderId: '467717966998',
    projectId: 'hot-or-not-4ff4b',
    storageBucket: 'hot-or-not-4ff4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyk48mSFTvuHG9hkiMnzjTb4xUkW7unF0',
    appId: '1:467717966998:ios:afb410f55096380569c6b7',
    messagingSenderId: '467717966998',
    projectId: 'hot-or-not-4ff4b',
    storageBucket: 'hot-or-not-4ff4b.appspot.com',
    iosBundleId: 'com.example.hotOrNot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyk48mSFTvuHG9hkiMnzjTb4xUkW7unF0',
    appId: '1:467717966998:ios:afb410f55096380569c6b7',
    messagingSenderId: '467717966998',
    projectId: 'hot-or-not-4ff4b',
    storageBucket: 'hot-or-not-4ff4b.appspot.com',
    iosBundleId: 'com.example.hotOrNot',
  );
}
